### ISSUE TITLE
able predict next validator

### ISSUE THREAD

**Issue by DmRos** [velas/JsWallet#111]
"You cannot move from the pool which is a validator or going to become one. Please use Request Exit feature instead."
message appears

Prerequisites:
Testnet, already staking in a pool

Steps to reproduce:

1. Staking > move stake > input valid amount and new pool address > apply 
2. Message allert pops up  "You cannot move from the pool which is a validator or going to become one. Please use Request Exit feature instead."

Expected result: one cannot be sure witch pool going validate next

Actual result: possible to predict next validator

![validator](https://user-images.githubusercontent.com/73913130/106898568-06b1b280-66fd-11eb-8949-ee1590c673eb.jpg)

Environment:
Build [0.13.21]
OS [Windows 7 x64]
Browser(s): Chrome 88.0.4324.104 // Opera 73.0.3856.344

**Comment by Corresponsible** [comment]
This means an epoch has passed since you had staked and now your pool (potentially) can become a validator or already is, so you can't move stake in this epoch, you can request exit that will be performed after this epoch is over. System doesn't know exactly which pool is going to become a validator.
